### ISSUE TITLE
create_analysis: ligne vide pour chaque select_one

### ISSUE THREAD

**Issue by RedEggplant1** [impact-initiatives/analysistools#20]
Sur l'output d'analysistools::create_analysis: Pourquoi est-ce que j'obtiens pour chaque select_one une ligne avec une option vide? (qui n'est pas équivalente à NA car j ai des valeurs NA pour cette question qui sont exclues à juste titre). Les autres valeurs pour ces questions sont correctes.

![MicrosoftTeams-image (7)](https://github.com/impact-initiatives/analysistools/assets/63230276/713c68f1-af3c-4502-9279-1319802b816e)
![MicrosoftTeams-image (8)](https://github.com/impact-initiatives/analysistools/assets/63230276/7887f4f2-5f1c-455e-a4ad-878ca3f33ca1)

**Comment by yannsay-impact** [comment]
```
library(analysistools)
mondataset <- analysistools::analysistools_MSNA_template_data[, "hoh"]

mondataset$hoh <- sample(c("no", "yes", "other", NA_character_), 
                              size = length(mondataset$hoh ), 
                              replace = T, 
                              prob = c(0.44,0.44,0.1,0.1))
my_surveyx <- srvyr::as_survey(mondataset)

mes_resultats <- create_analysis(my_surveyx, sm_sep = "/")
```

**Comment by yannsay-impact** [comment]
Line with NA will appear if there are missing values.
Before:
![image](https://github.com/impact-initiatives/analysistools/assets/79831444/e4eb9795-ac0d-401d-9a6c-16a084b7f1ef)
After:
![image](https://github.com/impact-initiatives/analysistools/assets/79831444/d21ce56a-b6d1-44a5-ae91-66a1816df046)
